core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('custom_login.urls', 'auth'), namespace='auth')),
    path('', include(('website.urls','website'),namespace='website')),
    path('event/', include(('mass.urls','mass'),namespace='mass')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate_email'),
    path('request-activation/', views.request_activation_email, name='request_activation_email'),
]

mass/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_event, name='create'),
    path('join/', views.join, name='join'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('leave/<int:id>/', views.leave, name='leave'),
    path('details/<uuid:uuid>/', views.details, name='details'),
]

website/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('user/', views.change_nickname, name='change_nickname'),
    path('user/<int:user_id>/', views.user_profile, name='user_profile'),
]

website/models.py
from django.db import models

from email_login.models import User

class UserNickname(models.Model):
    nickname = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nickname
    
    def random_nickname_generator():
        import random

        nicknames = [
        'RuneMaster', 'BladeOfDestiny', 'ShadowStriker', 'KnightOfValor', 'MysticMage', 
        'DragonSlayerX', 'ElvenArcher', 'DwarfSmith', 'NecroKnight', 'PhoenixRiderX', 
        'SilverSorcerer', 'WarlockLord', 'StormBringer', 'FrostKnight', 'DarkAssassin', 
        'FireWielder', 'ShadowHunter', 'IceMage', 'ThunderFist', 'GoldenWarrior', 
        'CrystalSeer', 'RuneWarrior', 'DragonTamer', 'ArcaneArcher', 'ShadowMage', 
        'SteelKnight', 'WindRider', 'BattleMage', 'GoblinCrusher', 'OrcBane', 
        'SilverRanger', 'RuneSlayer', 'MysticWarrior', 'DeathBringer', 'LightBearer', 
        'StormCaller', 'StoneGuardian', 'PhoenixKnight', 'DragonKnight', 'BladeDancer', 
        'IronClad', 'ShadowWalker', 'RuneHunter', 'StormWarrior', 'FlameWarden', 
        'RuneCraft', 'SpiritWalker', 'FireBlade', 'LightningStriker', 'IceRanger', 
        'RuneDefender', 'DuskMage', 'FrostGiant', 'StormWarden', 'ShadowFury', 
        'BladeMaster', 'WindWalker', 'RuneSentinel', 'StoneCrusher', 'IronGuard', 
        'PhoenixBlade', 'DragonWarden', 'ArcaneDefender', 'StormKnight', 'BlazeMage', 
        'RuneWarden', 'ShadowBlade', 'FrostWarden', 'LightningMage', 'WarriorMage', 
        'DarkRider', 'RuneWizard', 'DragonFury', 'ShadowKnight', 'StoneWarden', 
        'PhoenixWarden', 'IceKnight', 'StormRider', 'RuneBane', 'ShadowWizard', 
        'FlameKnight', 'LightningBlade', 'IronWarden', 'PhoenixMage', 'StormWizard', 
        'RuneWalker', 'FrostMage', 'BlazeKnight', 'ShadowWarden', 'RuneTamer', 
        'DragonWalker', 'WindKnight', 'IronMage', 'PhoenixRider', 'RuneRider', 
        'ShadowWalkerX', 'FrostKnightX', 'BlazeWarden', 'StormDefender', 'IronKnight'
        ]

        nickname = random.choice(nicknames) + str(random.randint(10,99))
        return nickname

website/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from email_login.models import User
from .models import UserNickname
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponseForbidden

from mass.models import Event

def index(request):
    return render(request, 'website/index.html')

@login_required
def user_profile(request, user_id):
    user = User.objects.get(id=user_id)
    events = Event.objects.filter(creator=user)
    
    try:
        nickname = UserNickname.objects.get(user=user).nickname
    except UserNickname.DoesNotExist:
        nickname = UserNickname.random_nickname_generator()
        UserNickname.objects.create(user=user, nickname=nickname)
        user_nickname = UserNickname.objects.get(user=user)
        user_nickname.nickname = nickname
        user_nickname.save()


    context = {
        'user': user,
        'nickname': nickname,
        'events': events
    }
    return render(request, 'website/user_profile.html', context)

@login_required
def change_nickname(request):
    print(request.user)
    if request.method == 'POST':
        nickname = request.POST.get('nickname')
        if nickname:
            user = request.user
            user_nickname, created = UserNickname.objects.get_or_create(user=user)
            user_nickname.nickname = nickname
            user_nickname.save()
            return redirect('website:user_profile', user_id=user.id)
    return redirect('website:user_profile', user_id=request.user.id)

templates/website/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <title>
        {% block title %}OSRS-Mass{% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous" defer></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous" defer></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

</head>

<body data-bs-theme="dark">
    {% include "website/navbar.html" %}

    {% block content %}

    {% endblock %}

    {% include "website/footer.html" %}

</body>

</html>

templates/website/footer.html
<div class="container">

    <footer class="text-center text-lg-start border-top mt-xl-5 pt-4">
        <div class="container p-4">
            <div class="row justify-content-center">
                <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                    <h5 class="text-uppercase text-center mb-4">Features</h5>
                    <ul class="list-unstyled mb-4 text-center">
                        <li><a href="#!" class="text-white">Mass Events</a></li>
                        <li><a href="#!" class="text-white">Calculators</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                    <h5 class="text-uppercase text-center mb-4">Help us</h5>
                    <ul class="list-unstyled text-center">
                        <li><a href="#!" class="text-white">Translations</a></li>
                        <li><a href="#!" class="text-white">Github</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="text-center p-3 border-top">
            &copy; Jonne Saloranta 2024
        </div>
    </footer>

</div>

templates/website/index.html
{% extends "website/base.html" %}

{% block content %}
<div class="container">
    <div class="row text-center pb-4 text-uppercase">
        <h2>OSRS-Mass</h2>
    </div>
</div>

<div class="container text-center mb-5">
    <form action="{% url 'mass:join' %}" method="GET">
        <div class="row justify-content-center">
            <div class="col-auto">
                <div class="input-group">
                    <input type="text" class="form-control" name="invite_code" id="invite-code" placeholder="Invite Code" />
                    <button type="submit" class="btn btn-success">Join Event</button>
                </div>
            </div>
        </div>
    </form>
</div>



<div class="container mb-3">
    <div class="row justify-content-center g-4">
        <div class="col-md-4">
            <div class="card h-100">
                <a href="{% url 'mass:create' %}" class="text-decoration-none">
                    <img src="/media/osrs-player.jpg" class="card-img-top object-fill -xxl-contain border rounded" alt="Runescape players" />
                    <div class="card-body">
                        <h5 class="card-title border-bottom pb-3">Create A Mass Event</h5>
                        <p class="card-text">
                            Create your own Mass Event and invite your friends to join you.
                        </p>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/website/navbar.html
{% load i18n %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark py-3 mb-4 border-bottom">
        <a href="{% url 'website:index' %}" class="navbar-brand d-flex align-items-center">{% trans "OSRS-MASS" %}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="{% trans 'Toggle navigation' %}">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a href="{% url 'website:index' %}" class="nav-link fs-5">{% trans "Home" %}</a></li>
                <li class="nav-item"><a href="{% url 'mass:index' %}" class="nav-link fs-5">{% trans "Events" %}</a></li>
                {% if user.is_authenticated %}

                <li class="nav-item"><a href="{% url 'website:user_profile' user_id=user.id %}" class="nav-link fs-5">{% trans "Profile" %}</a></li>

                {% if user.is_superuser %}
                <li class="nav-item"><a href="{% url 'admin:index' %}" class="nav-link fs-5">{% trans "Dashboard" %} <i class="bi bi-speedometer"></i></a></li>
                {% endif %}
                {% endif %}


                {% if not user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'auth:login' %}" class="nav-link fs-5">{% trans "Login" %}</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'auth:logout' %}" class="nav-link fs-5">{% trans "Logout" %}</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

templates/website/sidebar.html
{% load i18n %}

<div class="container-fluid p-0 d-flex h-100">
    <div id="bdSidebar" class="d-flex flex-column 
                    flex-shrink-0 
                    p-3 bg-success
                    text-white offcanvas-md offcanvas-start">
        <a href="#" class="navbar-brand">
        </a>
        <hr>
        <ul class="mynav nav nav-pills flex-column mb-auto">
            <li class="nav-item mb-1">
                <a href="#">
                    <i class="fa-regular fa-user"></i>
                    Profile
                </a>
            </li>

            <li class="nav-item mb-1">
                <a href="#">
                    <i class="fa-regular fa-bookmark"></i>
                    Saved Articles
                    <span class="notification-badge">5</span>
                </a>
            </li>
            <li class="nav-item mb-1">
                <a href="#">
                    <i class="fa-regular fa-newspaper"></i>
                    Articles
                </a>
            </li>
            <li class="nav-item mb-1">
                <a href="#">
                    <i class="fa-solid fa-archway"></i>
                    Institutions
                </a>
            </li>
            <li class="nav-item mb-1">
                <a href="#">
                    <i class="fa-solid fa-graduation-cap"></i>
                    Organizations
                </a>
            </li>

            <li class="sidebar-item  nav-item mb-1">
                <a href="#" class="sidebar-link collapsed" data-bs-toggle="collapse" data-bs-target="#settings" aria-expanded="false" aria-controls="settings">
                    <i class="fas fa-cog pe-2"></i>
                    <span class="topic">Settings </span>
                </a>
                <ul id="settings" class="sidebar-dropdown list-unstyled collapse" data-bs-parent="#sidebar">
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">
                            <i class="fas fa-sign-in-alt pe-2"></i>
                            <span class="topic"> Login</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">
                            <i class="fas fa-user-plus pe-2"></i>
                            <span class="topic">Register</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="#" class="sidebar-link">
                            <i class="fas fa-sign-out-alt pe-2"></i>
                            <span class="topic">Log Out</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
        <hr>
        <div class="d-flex">

            <i class="fa-solid fa-book  me-2"></i>
            <span>
                <h6 class="mt-1 mb-0">
                    Geeks for Geeks Learning Portal
                </h6>
            </span>
        </div>
    </div>

    <div class="bg-light flex-fill">
        <div class="p-2 d-md-none d-flex text-white bg-success">
            <a href="#" class="text-white" data-bs-toggle="offcanvas" data-bs-target="#bdSidebar">
                <i class="fa-solid fa-bars"></i>
            </a>
            <span class="ms-3">GFG Portal</span>
        </div>
        <div class="p-4">
            <nav style="--bs-breadcrumb-divider:'>';font-size:14px">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <i class="fa-solid fa-house"></i>
                    </li>
                    <li class="breadcrumb-item">Learning Content</li>
                    <li class="breadcrumb-item">Next Page</li>
                </ol>
            </nav>

            <hr>
            <div class="row">
                <div class="col">
                    <p>Page content goes here</p>
                </div>
            </div>
        </div>

    </div>
</div>

templates/website/user_events.html
<div class="container mb-3">
    <div class="row justify-content-center g-4 mb-3">
        <div class="col-md-4">
            {% if events %}
            {% for event in events %}
            <div class="card h-100">
                <h3 class="card-title text-center p-3">{{ event.name|upper }}</h3>
                <img src="{{event.get_event_image_url}}" class="card-img-top object-fill -xxl-contain border rounded" alt="Event image" />
                <div class="card-body">

                    <p class="card-text">{{ event.description|truncatewords:15 }}</p>
                    {% if event.start_date|is_in_progress:event.end_date %}
                    <p class="card-text text-warning fw-bold"><i class="bi bi-clock-fill"></i> In Progress!</p>
                    {% else %}
                    {% if event.start_date|starts_in_10_minutes %}
                    <p class="card-text text-info fw-bold"><i class="bi bi-clock-fill"></i> Starting in &lt;10min!</p>
                    {% else %}
                    <p class="card-text text-success fw-bold"><i class="bi bi-clock-fill"></i> Until Starts: {{ event.start_date|timeuntil_or_ongoing }}</p>
                    {% endif %}
                    {% endif %}

                    <p class="card-text"><i class="bi bi-hourglass-top"></i> Starts: {{ event.start_date|date:'H:i d-m-Y' }}</p>
                    <p class="card-text"><i class="bi bi-hourglass-bottom"></i> Ends: {{ event.end_date|date:'H:i d-m-Y' }}</p>
                    <p class="card-text"><i class="bi bi-geo-alt-fill"></i> Location: {{ event.location }}</p>
                    <p class="card-text">Code: {{ event.invite_code }}</p>

                    <div class="text-center">
                        <p class="card-text">Requirements:</p>
                        {% if event.requirements.all %}
                        {% for requirement in event.requirements.all %}
                        <p><span class="badge bg-success">{% trans "Yes" %}</span>
                            {% if requirement.wiki_url %}
                            <a href="{{ requirement.wiki_url }}" target="_blank">{{requirement}}</a>
                            {% else %}
                            {{requirement}}
                            {% endif %}
                        </p>
                        {% if requirement.sub_requirements.all %}
                        {% for sub_requirement in requirement.sub_requirements.all %}
                        <p><span class="badge bg-success">{% trans "Yes" %}</span> {{sub_requirement}}</p>
                        {% endfor %}
                        {% endif %}
                        {% endfor %}
                        <a href="{% url 'mass:details' id=event.id %}">View details</a>
                        {% else %}
                        <p><span class="badge bg-success">{% trans "Yes" %}</span> No requirements</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="card h-100">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-center">No events</h5>
                    <p class="card-text text-center">You have not created any events yet.😢</p>
                    <a href="{% url 'mass:create' %}" class="btn btn-primary mt-auto">Create event</a>
                </div>
            </div>
            {% endif %}

        </div>
    </div>
</div>

templates/website/user_profile.html
{% extends "website/base.html" %}

{% load static %}
{% load i18n %}
{% load event_filters %}

{% block title %}User Profile{% endblock %}
{% block content %}
<div class="container">
    <div class="row text-center pb-4 text-uppercase">
        <h2>OSRS-Mass</h2>
    </div>
</div>

{% include "mass/container_events_small.html" %}

<div class="container mb-3">
    <div class="row justify-content-center g-4 mb-3">
        <div class="col-md-6">
            <div class="card h-100">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Account details</h5>
                    <p class="card-text">Email: {{ user.email }}</p>
                    <p class="card-text">Name: {{ user.name }} {{ user.lastname }}</p>
                    <p class="card-text">Nickname: {{ nickname }}</p>
                    <form action="{% url 'website:change_nickname' %}" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="text" class="form-control" name="nickname" placeholder="{{ nickname }}" id="nickname" />
                        </div>
                        <button type="submit" class="btn btn-primary mt-auto">Change Nickname</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card h-100">
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">Change Password</h5>
                    <form action="#" method="POST" class="d-flex flex-column h-100">
                        {% csrf_token %}
                        <div class="mb-3">
                            <input type="password" class="form-control" name="old_password" placeholder="Old Password" id="old-password" />
                        </div>
                        <div class="mb-3">
                            <input type="password" class="form-control" name="new_password1" placeholder="New Password" id="new-password" />
                        </div>
                        <div class="mb-3">
                            <input type="password" class="form-control" name="new_password2" placeholder="Confirm New Password" id="confirm-new-password" />
                        </div>
                        <button type="submit" class="btn btn-primary">Change Password</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}