core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('custom_login.urls', 'auth'), namespace='auth')),
    path('', include(('website.urls','website'),namespace='website')),
    path('event/', include(('mass.urls','mass'),namespace='mass')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

custom_login/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate_email'),
    path('request-activation/', views.request_activation_email, name='request_activation_email'),
]

custom_login/models.py
from django.db import models

# Create your models here.

custom_login/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model

class UserLoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):

        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        
        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")
            if not user.is_active:
                raise forms.ValidationError("This user is not longer active.")
        return super(UserLoginForm, self).clean(*args, **kwargs)
    
user = get_user_model()


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label='Email Address')
    email2 = forms.EmailField(label='Confirm Email')
    name = forms.CharField(label='Name')
    lastname = forms.CharField(label='Lastname')
    password = forms.CharField(widget=forms.PasswordInput, label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Confirm Password')

    class Meta:
        model = user
        fields = [
            'email',
            'email2',
            'name',
            'lastname',
            'password',
            'password2',
        ]
    
    def clean(self):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        name = self.cleaned_data.get('name')
        lastname = self.cleaned_data.get('lastname')
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if email != email2:
            raise forms.ValidationError("Emails must match")        
        
        email_qs = user.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered")
        
        if password != password2:
            raise forms.ValidationError("Passwords must match")
        return super(UserRegisterForm, self).clean()
    
class RequestActivationEmailForm(forms.Form):
    email = forms.EmailField(label='Email Address')
    

custom_login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .forms import UserLoginForm, UserRegisterForm, RequestActivationEmailForm
from django.contrib import messages
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from .tokens import account_activation_token
from django.core.mail import EmailMessage, get_connection
from decouple import config
from custom_login.email_activation import activateEmail, activate
from django.urls import reverse, reverse_lazy

def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('mass:index'))
    next = request.GET.get('next')
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        
        user = authenticate(email=email, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                if next:
                    return redirect(next)
                return redirect("mass:index")
            else:
                messages.error(request, 'Your account is not active. Please check your email for activation instructions.')
        else:
            messages.error(request, 'Invalid email or password.')
    
    context = {
        'form': form,
    }
    return render(request, "login.html", context)

def register_view(request):
    if request.user.is_authenticated:
        return redirect("mass:index")
    next = request.GET.get('next')
    form = UserRegisterForm(request.POST or None)
    
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get("password")
        user.set_password(password)
        resend_api_key = config('RESEND_API_KEY')
        if resend_api_key and config('USE_EMAIL_ACTIVATION', default=False, cast=bool):
            user.is_active = False
            user.save()
            activateEmail(request, user, form.cleaned_data.get("email"))
            messages.success(request, "We have sent you an email. Please confirm your email address to complete registration.")
        else:
            user.is_active = True
            user.save()
            login(request, user)
            messages.success(request, 'Your account has been created.')
            if next:
                return redirect(next)
            return redirect("mass:index")
        
        if next:
            return redirect(next)
        return redirect("mass:index")
    
    context = {
        'form': form,
    }
    return render(request, "register.html", context)

def logout_view(request):
    logout(request)
    messages.success(request, 'You have been successfully logged out.')
    return redirect("mass:index")

def request_activation_email(request):
    if request.method == 'POST':
        form = RequestActivationEmailForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user_model = get_user_model()
            try:
                user = user_model.objects.get(email=email, is_active=False)
                activateEmail(request, user, email)
                messages.success(request, "Activation email will be sent if the email is associated with an existing account.")
            except user_model.DoesNotExist:
                messages.success(request, "Activation email will be sent if the email is associated with an existing account.")
            return redirect('auth:request_activation_email')
    else:
        form = RequestActivationEmailForm()

    return render(request, 'request_activation_email.html', {'form': form})

custom_login/templates/activate_email.html
{% autoescape off %}

<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            color: #333;
        }

        .container {
            max-width: 600px;
            margin: 20px auto;
            padding: 20px;
            background-color: #ffffff;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-shadow: 0 2px 3px rgba(0, 0, 0, 0.1);
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            margin-top: 20px;
            background-color: #00336a;
            color: #ffffff;
            text-decoration: none;
            font-size: 16px;
            font-weight: bold;
            border-radius: 4px;
        }

        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 0.8em;
            color: #777;
        }
    </style>
</head>

<body>
    <div class="container">
        <h2>Account Activation</h2>
        <p>Hi <b>{{ user.name }} {{ user.lastname }}</b>,</p>
        <p>Please click the button below to activate your account:</p>


        <a href="http://{{ domain }}{% url 'activate_email' uidb64=uid token=token %}" class="button">Activate Account</a>

        <p>If you didn't request this, you can ignore this email.</p>
        <p>Thanks,</p>
        <p>OSRS Events Team</p>
        <p class="footer">&copy; 2024 Jonne Saloranta. All rights reserved.</p>
    </div>
</body>

</html>

{% endautoescape %}

custom_login/templates/login.html
{% extends "website/base.html" %}
{% load i18n %}
{% load static %}

{% block title %}
{% trans "Login" %}
{% endblock %}


{% block content %}

<div class="container-sm">
    <div class="row justify-content-center mt-5">
        <div class="col-lg-4 col-md-6 col-sm-6">
            <main class="form-signin m-auto">
                <form action="{% url 'auth:login' %}" method="post">
                    {% csrf_token %}
                    <h1 class="h3 mb-3 fw-normal text-center">{% trans "Please login" %}</h1>

                    <div class="form-floating my-2">
                        <input type="email" class="form-control" name="email" id="email" placeholder="email@example.com" required>
                        <label for="email">{% trans "Email"%}</label>
                    </div>

                    <div class="form-floating my-2">
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
                        <label for="password">{% trans "Password" %}</label>
                    </div>
                    <input class="btn btn-primary w-100 py-2" type="submit" value="{% trans 'Login' %}">
                </form>

                {% if USE_EMAIL_ACTIVATION %}
                <div class="container text-center py-3">
                    <p>{% trans "Need your account activated?"%}</p>
                    <a href="{% url 'auth:request_activation_email' %}">{% trans "Request activation"%}</a>
                </div>
                {% endif %}

                <div class="container text-center py-3">
                    <p>{% trans "Need an account?" %}</p>
                    <a href="{% url 'auth:register' %}">{% trans "Register here" %}</a>
                </div>
            </main>
        </div>
    </div>
</div>

{% endblock %}

custom_login/templates/register.html
{% extends "website/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}Register{% endblock %}


{% block content %}

<div class="container-sm">
    <div class="row justify-content-center mt-5">
        <div class="col-lg-4 col-md-6 col-sm-6">
            <main class="form-signin m-auto">
                <form action="{%url 'auth:register' %}" method="post">
                    {% csrf_token %}
                    <h1 class="h3 mb-3 fw-normal text-center">{%trans 'Sign up' %}</h1>

                    <div class="form-floating my-2">
                        <input type="text" class="form-control" name="name" id="name" placeholder="Firstname" required>
                        <label for="name">{%trans 'Firstname' %}</label>
                    </div>

                    <div class="form-floating my-2">
                        <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Lastname" required>
                        <label for="lastname">{%trans 'Lastname' %}</label>
                    </div>

                    <div class="form-floating my-2">
                        <input type="email" class="form-control" name="email" id="email" placeholder="name@example.com" required>
                        <label for="email">{%trans 'Email' %}</label>
                    </div>

                    <div class="form-floating my-2">
                        <input type="email" class="form-control" name="email2" id="email2" placeholder="name@example.com" required>
                        <label for="email2">{%trans 'Repeat Email' %}</label>
                    </div>

                    <div class="form-floating my-2">
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password" required>
                        <label for="password">{%trans 'Password' %}</label>
                    </div>

                    <div class="form-floating my-2">
                        <input type="password" class="form-control" name="password2" id="password2" placeholder="Password" required>
                        <label for="password2">{%trans 'Repeat Password' %}</label>
                    </div>

                    <input class="btn btn-primary w-100 py-2" type="submit" value="{% trans 'Register' %}">
                </form>

                <div class="container text-center py-3">
                    <p>{%trans 'Already have an account?' %}</p>
                    <a href="{%url 'auth:login' %}">{%trans 'Login' %}</a>
                </div>
            </main>
        </div>
    </div>
</div>
{% endblock %}

custom_login/templates/request_activation_email.html
{% extends "website/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}Request activation{% endblock %}


{% block content %}
<div class="container text-center">
    <h2>{% trans 'Request account activation' %}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary py-2" type="submit" value="{% trans 'Send request'%}">
    </form>
</div>
{% endblock %}